# NumPy and Linear Algebra Foundations for Machine Learning

This notebook develops the numerical foundations used throughout machine learning, moving from array operations to ML-oriented calculations and core linear-algebra concepts.

**Topics covered**

- NumPy arrays, shape, data types, reshaping, indexing, and slicing
- Vectorized arithmetic, reductions, and broadcasting
- Boolean indexing and data selection
- Core machine-learning calculations implemented with NumPy
- Euclidean and Manhattan distance
- Accuracy and mean-squared error
- Variance-based feature selection
- Nearest-neighbor search
- Dot products and matrix multiplication
- Identity, transpose, inverse, and pseudoinverse
- The common machine-learning transformation \(XW+b\)


## 1. Import NumPy

In [53]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)

## 2. Creating and inspecting arrays

Machine-learning datasets are commonly represented as arrays. For a two-dimensional feature matrix \(X\), rows usually represent **instances** and columns represent **features**.

In [54]:
a = np.array([1, 2, 3, 4])

X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("1-D array:")
print(a)

print("\n2-D array:")
print(X)

print("\nshape:", X.shape)
print("number of dimensions:", X.ndim)
print("dtype:", X.dtype)

1-D array:
[1 2 3 4]

2-D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

shape: (3, 4)
number of dimensions: 2
dtype: int64


### Common constructors

In [55]:
print("zeros:")
print(np.zeros((2, 4), dtype=int))

print("\nones:")
print(np.ones((2, 3)))

print("\nfull:")
print(np.full((2, 3), np.pi))

print("\narange:")
print(np.arange(0, 12, 2))

zeros:
[[0 0 0 0]
 [0 0 0 0]]

ones:
[[1. 1. 1.]
 [1. 1. 1.]]

full:
[[3.142 3.142 3.142]
 [3.142 3.142 3.142]]

arange:
[ 0  2  4  6  8 10]


### Checking array shape

One of the array exercises asked for a function that determines whether an array is a square matrix. This is a simple example of using dimensionality and shape information directly.

In [56]:
def is_square(X):
    return isinstance(X, np.ndarray) and X.ndim == 2 and X.shape[0] == X.shape[1]

examples = [
    np.arange(9).reshape(3, 3),
    np.arange(12).reshape(3, 4),
    np.arange(8)
]

for X_example in examples:
    print(X_example.shape, "->", is_square(X_example))

(3, 3) -> True
(3, 4) -> False
(8,) -> False


## 3. Reshaping arrays

`reshape` changes how the same elements are organized. The total number of elements must remain unchanged.

In [57]:
a = np.arange(16)
print("Original:")
print(a)

A = a.reshape(4, 4)
print("\n4 x 4:")
print(A)

B = A.reshape(2, 2, 4)
print("\n2 x 2 x 4:")
print(B)

print("\nFlattened:")
print(B.reshape(-1))

Original:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

4 x 4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

2 x 2 x 4:
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

Flattened:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


## 4. Indexing and slicing

Indexing is central to machine-learning preprocessing because it is how we select instances, features, and subsets of data.

In [58]:
A = np.arange(20).reshape(4, 5)
print(A)

print("\nSingle element A[2, 3]:", A[2, 3])

print("\nSecond column:")
print(A[:, 1])

print("\nFirst two rows, columns 1 onward:")
print(A[:2, 1:])

print("\nEvery other row and column:")
print(A[::2, ::2])

print("\nReverse rows:")
print(A[::-1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Single element A[2, 3]: 13

Second column:
[ 1  6 11 16]

First two rows, columns 1 onward:
[[1 2 3 4]
 [6 7 8 9]]

Every other row and column:
[[ 0  2  4]
 [10 12 14]]

Reverse rows:
[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


### Integer-array indexing

In [59]:
np.random.seed(0)
A = np.random.randint(0, 10, size=(4, 5))
print(A)

rows = np.array([0, 2, 3])
cols = np.array([1, 4, 0])

print("\nSelected elements:")
print(A[rows, cols])

print("\nDiagonal of the largest square portion:")
n = min(A.shape)
print(A[np.arange(n), np.arange(n)])

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]
 [6 7 7 8 1]]

Selected elements:
[0 1 6]

Diagonal of the largest square portion:
[5 3 8 8]


## 5. References, Views, and Copying

NumPy arrays can share underlying data. Directly referencing an existing array does not create an independent copy. This matters when preprocessing data because an unintended modification can propagate to another variable.

In [60]:
A = np.arange(9).reshape(3, 3)
B = A
B[0, 0] = 100

print("A after changing B:")
print(A)

A = np.arange(9).reshape(3, 3)
B = np.copy(A)
B[0, 0] = 100

print("\nA after changing an independent copy:")
print(A)

A after changing B:
[[100   1   2]
 [  3   4   5]
 [  6   7   8]]

A after changing an independent copy:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 6. Vectorized arithmetic and reductions

NumPy applies arithmetic element by element. Reductions such as `sum`, `mean`, `max`, and `argmax` summarize arrays without explicit Python loops.

In [61]:
A = np.arange(12).reshape(3, 4)

print("A:")
print(A)

print("\nA + 5:")
print(A + 5)

print("\nA squared:")
print(A ** 2)

print("\nColumn means:")
print(np.mean(A, axis=0))

print("\nRow maxima:")
print(np.max(A, axis=1))

print("\nIndex of largest element in each row:")
print(np.argmax(A, axis=1))

A:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

A + 5:
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

A squared:
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]

Column means:
[4. 5. 6. 7.]

Row maxima:
[ 3  7 11]

Index of largest element in each row:
[3 3 3]


### Loop Implementation versus NumPy

Implementing the same operation with both explicit loops and NumPy highlights the difference between step-by-step computation and vectorized numerical programming. In practical machine-learning workflows, the vectorized form is usually more concise and efficient.

In [62]:
def max_loop(X):
    mx = -np.inf
    for value in np.nditer(X, flags=["zerosize_ok"]):
        if value > mx:
            mx = value
    return mx

def sum_loop(X):
    total = 0
    for value in np.nditer(X, flags=["zerosize_ok"]):
        total += value
    return total

X = np.array([[4, 2, 9], [1, 7, 3]])

print("max_loop:", max_loop(X))
print("np.max:   ", np.max(X))
print("sum_loop:", sum_loop(X))
print("np.sum:   ", np.sum(X))

max_loop: 9
np.max:    9
sum_loop: 26
np.sum:    26


### Vectorization timing example

In [63]:
import time

def add_with_loops(A, B):
    C = np.zeros_like(A)
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            C[i, j] = A[i, j] + B[i, j]
    return C

np.random.seed(1)
A = np.random.random((500, 500))
B = np.random.random((500, 500))

start = time.perf_counter()
C_loop = add_with_loops(A, B)
loop_time = time.perf_counter() - start

start = time.perf_counter()
C_vectorized = A + B
vectorized_time = time.perf_counter() - start

print("same result:", np.allclose(C_loop, C_vectorized))
print(f"loop time:       {loop_time:.6f} s")
print(f"vectorized time: {vectorized_time:.6f} s")

same result: True
loop time:       0.462749 s
vectorized time: 0.000844 s


## 7. Broadcasting

Broadcasting lets NumPy combine arrays with different but compatible shapes. Two trailing dimensions are compatible when they are equal or when one of them is 1.

In [64]:
np.random.seed(2)

A = np.random.randint(0, 10, size=(4, 5))
row = np.random.randint(0, 10, size=(1, 5))
column = np.random.randint(0, 10, size=(4, 1))

print("A:")
print(A)

print("\nA + row:")
print(A + row)

print("\nA + column:")
print(A + column)

A:
[[8 8 6 2 8]
 [7 2 1 5 4]
 [4 5 7 3 6]
 [4 3 7 6 1]]

A + row:
[[11 13 14  6 14]
 [10  7  9  9 10]
 [ 7 10 15  7 12]
 [ 7  8 15 10  7]]

A + column:
[[11 11  9  5 11]
 [16 11 10 14 13]
 [ 6  7  9  5  8]
 [ 4  3  7  6  1]]


### Checking Broadcasting Compatibility

The compatibility rule can be implemented directly by comparing array shapes from the last dimension backward.

In [65]:
def broadcast_compatible(X, Y):
    for i in range(-1, -min(len(X.shape), len(Y.shape)) - 1, -1):
        if X.shape[i] != Y.shape[i] and X.shape[i] != 1 and Y.shape[i] != 1:
            return False
    return True

shapes = [
    np.zeros((4, 5)),
    np.zeros((1, 5)),
    np.zeros((4, 1)),
    np.zeros((5, 4, 1)),
    np.zeros(8)
]

for X in shapes:
    for Y in shapes:
        if broadcast_compatible(X, Y):
            print(f"{X.shape} and {Y.shape} are compatible")

(4, 5) and (4, 5) are compatible
(4, 5) and (1, 5) are compatible
(4, 5) and (4, 1) are compatible
(4, 5) and (5, 4, 1) are compatible
(1, 5) and (4, 5) are compatible
(1, 5) and (1, 5) are compatible
(1, 5) and (4, 1) are compatible
(1, 5) and (5, 4, 1) are compatible
(4, 1) and (4, 5) are compatible
(4, 1) and (1, 5) are compatible
(4, 1) and (4, 1) are compatible
(4, 1) and (5, 4, 1) are compatible
(4, 1) and (8,) are compatible
(5, 4, 1) and (4, 5) are compatible
(5, 4, 1) and (1, 5) are compatible
(5, 4, 1) and (4, 1) are compatible
(5, 4, 1) and (5, 4, 1) are compatible
(5, 4, 1) and (8,) are compatible
(8,) and (4, 1) are compatible
(8,) and (5, 4, 1) are compatible
(8,) and (8,) are compatible


## 8. Boolean indexing and data selection

Boolean masks are especially useful for filtering datasets based on conditions.

In [66]:
np.random.seed(3)
X = np.random.randint(0, 10, size=(8, 5))
print("X:")
print(X)

mask = X[:, 0] > 5
print("\nRows where feature 0 > 5:")
print(X[mask])

X:
[[8 9 3 8 8]
 [0 5 3 9 9]
 [5 7 6 0 4]
 [7 8 1 6 2]
 [2 1 3 5 8]
 [1 8 7 8 1]
 [0 5 4 1 5]
 [4 7 6 0 0]]

Rows where feature 0 > 5:
[[8 9 3 8 8]
 [7 8 1 6 2]]


### Variance-Based Feature Selection

Selecting the \(n\) features with the largest variance demonstrates how column statistics and indexing can be combined. Variance alone is not a complete feature-selection strategy, but it provides a simple example of ranking features numerically.

In [67]:
def select_features(X, n):
    variances = np.var(X, axis=0)
    order = np.argsort(variances)
    selected = order[-n:]
    return X[:, selected], selected, variances

np.random.seed(12)
X = np.random.randint(0, 10, size=(10, 5))

X_selected, selected_columns, variances = select_features(X, 2)

print("feature variances:", variances)
print("selected columns:", selected_columns)
print("\nselected data:")
print(X_selected)

feature variances: [11.61  3.96  9.56  7.69  4.36]
selected columns: [2 0]

selected data:
[[2 6]
 [1 0]
 [6 9]
 [9 8]
 [7 3]
 [0 6]
 [0 9]
 [1 9]
 [1 0]
 [5 3]]


### Filtering instances by a feature threshold

In [68]:
def select_instances(X, feature, threshold):
    return X[X[:, feature] > threshold]

np.random.seed(13)
X = np.random.randint(0, 10, size=(8, 5))

print("Original data:")
print(X)

print("\nInstances where feature 2 > 6.5:")
print(select_instances(X, 2, 6.5))

Original data:
[[2 0 0 6 2]
 [4 9 3 4 2]
 [6 5 9 4 2]
 [0 3 5 3 6]
 [5 1 2 8 8]
 [6 2 4 5 7]
 [3 5 8 3 8]
 [5 1 8 1 7]]

Instances where feature 2 > 6.5:
[[6 5 9 4 2]
 [3 5 8 3 8]
 [5 1 8 1 7]]


## 9. Core Machine-Learning Calculations from Scratch

Several common machine-learning calculations can be implemented directly with NumPy. Building them explicitly makes the connection between array operations and ML algorithms easier to see.

### Dot product

In [69]:
def dot(x1, x2):
    if x1.shape[0] != x2.shape[0]:
        raise ValueError("x1 and x2 must have the same length")

    result = 0
    for i in range(x1.shape[0]):
        result += x1[i] * x2[i]
    return result

x1 = np.array([1, -2, 3])
x2 = np.array([4, 0, 2])

print("custom dot:", dot(x1, x2))
print("np.dot:    ", np.dot(x1, x2))

custom dot: 10
np.dot:     10


### Euclidean and Manhattan distance

In [70]:
def euclidean_dist(x1, x2):
    if x1.shape[0] != x2.shape[0]:
        raise ValueError("x1 and x2 must have the same length")

    total = 0.0
    for i in range(x1.shape[0]):
        diff = x1[i] - x2[i]
        total += diff * diff
    return np.sqrt(total)

def manhattan_dist(x1, x2):
    if x1.shape[0] != x2.shape[0]:
        raise ValueError("x1 and x2 must have the same length")

    total = 0.0
    for i in range(x1.shape[0]):
        total += abs(x1[i] - x2[i])
    return total

x1 = np.array([0, 1])
x2 = np.array([-2, -2])

print("Euclidean distance:", euclidean_dist(x1, x2))
print("Manhattan distance:", manhattan_dist(x1, x2))

Euclidean distance: 3.605551275463989
Manhattan distance: 5.0


### Accuracy and mean-squared error

In [71]:
def accuracy(predictions, y):
    if predictions.shape != y.shape:
        raise ValueError("predictions and y must have the same shape")

    correct = 0
    for i in range(predictions.shape[0]):
        if predictions[i] == y[i]:
            correct += 1
    return correct / predictions.shape[0]

def mse(predictions, y):
    if predictions.shape != y.shape:
        raise ValueError("predictions and y must have the same shape")

    total = 0.0
    for i in range(predictions.shape[0]):
        diff = float(predictions[i]) - float(y[i])
        total += diff * diff
    return total / predictions.shape[0]

class_predictions = np.array([1, 1, 0, 1])
class_targets = np.array([1, 0, 0, 1])

regression_predictions = np.array([1.0, 3.0, 1.0])
regression_targets = np.array([0.0, 1.0, 3.0])

print("accuracy:", accuracy(class_predictions, class_targets))
print("MSE:", mse(regression_predictions, regression_targets))

accuracy: 0.75
MSE: 3.0


## 10. Nearest-neighbor search with NumPy

Nearest-neighbor methods depend on the same distance calculations introduced above. The first function finds the closest row in a reference dataset. The second finds a nearest neighbor for every row in another dataset using broadcasting.

In [72]:
def nearest_neighbor(X, x):
    differences = X - x
    squared_distances = np.sum(differences * differences, axis=1)
    return np.argmin(squared_distances)

def nearest_neighbors(X1, X2):
    # D[i, j] = squared Euclidean distance between X1[i] and X2[j]
    differences = X1[:, None, :] - X2[None, :, :]
    squared_distances = np.sum(differences * differences, axis=2)
    return np.argmin(squared_distances, axis=0)

X_reference = np.array([
    [8, 6],
    [7, 9],
    [6, 0],
    [8, 9],
    [7, 6]
])

x = np.array([4, 0])

print("nearest index to", x, ":", nearest_neighbor(X_reference, x))

X_query = np.array([
    [5, 3],
    [6, 8],
    [2, 1]
])

print("nearest indices for all query points:")
print(nearest_neighbors(X_reference, X_query))

nearest index to [4 0] : 2
nearest indices for all query points:
[2 1 2]


## 11. Linear algebra essentials

Many machine-learning models can be written compactly with vectors and matrices. The next examples summarize the linear-algebra operations used repeatedly in regression, classification, dimensionality reduction, and neural networks.

### Vector dot product

In [73]:
x = np.array([2, 7, 1])
y = np.array([8, 2, 8])

print("np.dot(x, y) =", np.dot(x, y))

np.dot(x, y) = 38


### Element-wise multiplication versus matrix multiplication

`A * B` multiplies corresponding elements. `A @ B` (or `np.matmul(A, B)`) performs matrix multiplication.

In [74]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 3],
              [5, 6]])

print("Element-wise A * B:")
print(A * B)

print("\nMatrix product A @ B:")
print(A @ B)

Element-wise A * B:
[[ 2  6]
 [15 24]]

Matrix product A @ B:
[[12 15]
 [26 33]]


### Matrix multiplication and shape compatibility

In [75]:
np.random.seed(4)

A = np.random.randint(-1, 4, size=(4, 2))
B = np.random.randint(-1, 4, size=(2, 3))
C = A @ B

print("A shape:", A.shape)
print("B shape:", B.shape)
print("C = A @ B shape:", C.shape)
print("\nC:")
print(C)

A shape: (4, 2)
B shape: (2, 3)
C = A @ B shape: (4, 3)

C:
[[ 0 -1  3]
 [-1 -2 -4]
 [ 0 -1  3]
 [ 3  8  6]]


### Identity matrix and transpose

In [76]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

I = np.eye(A.shape[1], dtype=int)

print("A:")
print(A)

print("\nA @ I:")
print(A @ I)

print("\nA.T:")
print(A.T)

A:
[[1 2 3]
 [4 5 6]]

A @ I:
[[1 2 3]
 [4 5 6]]

A.T:
[[1 4]
 [2 5]
 [3 6]]


### Inverse and pseudoinverse

A square nonsingular matrix has an inverse. The pseudoinverse extends the idea to rectangular or singular matrices and appears in least-squares problems.

In [77]:
A = np.array([
    [2.0, 1.0],
    [1.0, 3.0]
])

A_inv = np.linalg.inv(A)

print("A inverse:")
print(A_inv)

print("\nA @ A_inv:")
print(A @ A_inv)

X = np.array([
    [1.0, 0.0],
    [1.0, 1.0],
    [1.0, 2.0],
    [1.0, 3.0]
])

X_pinv = np.linalg.pinv(X)

print("\nPseudoinverse shape:", X_pinv.shape)
print("X_pinv @ X:")
print(X_pinv @ X)

A inverse:
[[ 0.6 -0.2]
 [-0.2  0.4]]

A @ A_inv:
[[ 1.  0.]
 [-0.  1.]]

Pseudoinverse shape: (2, 4)
X_pinv @ X:
[[ 1. -0.]
 [ 0.  1.]]


## 12. A common machine-learning matrix operation: \(XW+b\)

A recurring pattern in linear regression, logistic regression, and neural networks is:

\[
Z = XW + b
\]

where:

- \(X\): input data, shape `(n_instances, n_features)`
- \(W\): learned weights
- \(b\): bias vector
- \(Z\): transformed output

Broadcasting adds the same bias vector to every row.

In [78]:
np.random.seed(5)

n_instances = 6
n_features = 4
n_outputs = 3

X = np.random.randint(-1, 4, size=(n_instances, n_features))
W = np.random.randint(-1, 2, size=(n_features, n_outputs))
b = np.random.randint(-1, 2, size=n_outputs)

Z = X @ W + b

print("X shape:", X.shape)
print("W shape:", W.shape)
print("b shape:", b.shape)
print("Z shape:", Z.shape)

print("\nZ = X @ W + b:")
print(Z)

X shape: (6, 4)
W shape: (4, 3)
b shape: (3,)
Z shape: (6, 3)

Z = X @ W + b:
[[-2  2  3]
 [ 1 -1  1]
 [-1  4  0]
 [ 0  4 -4]
 [ 0  2  0]
 [ 1  1  0]]


## Key Takeaways

- NumPy arrays provide the numerical representation used throughout the later machine-learning repositories.
- Shape, indexing, slicing, and boolean masks are the foundation of data preprocessing.
- Vectorization replaces many slow Python loops with concise array expressions.
- Broadcasting enables operations such as adding one bias vector to every instance.
- Distances, accuracy, MSE, feature selection, and nearest-neighbor search can all be expressed directly with NumPy.
- Dot products and matrix multiplication provide the mathematical language behind many machine-learning models.
- The transformation \(XW+b\) connects the NumPy and linear-algebra foundations directly to later regression, classification, and neural-network models.